### ISSUE TITLE
Publish Python plugins to PyPI

### ISSUE THREAD

**Issue by ghost** [arcalot/arcaflow-plugins#34] opened 2022-08-25 08:58 UTC
In order to make Python plugins consumable by tools like [Krkn](https://github.com/redhat-chaos/krkn), the Python plugins should be published to PyPI. We already have a namespace set up, it's only a matter of porting the [SDK publishing process](https://github.com/arcalot/arcaflow-plugin-sdk-python/blob/main/.github/workflows/build.yml) and apply it to the [build process](#2)

**Comment by dustinblack** [comment] 2022-11-08 08:06
I think this one is covered now, and the issue is associated with the arcaflow-plugins repo, which should be retired soon. Can we close this one out? @sandrobonazzola @janosdebugs

**Closed as completed** 2022-11-08 20:53 UTC
Labels: enhancement
